package oba.backend.server.scheduler;

import lombok.RequiredArgsConstructor;
import oba.backend.server.service.QuizPipelineService;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
public class QuizScheduler {

    private final QuizPipelineService quizPipelineService;

    @Scheduled(cron = "0 0 9 * * *", zone = "Asia/Seoul")
    public void autoGenerateDailyQuizzes() {
        System.out.println("[스케줄러] 오늘 기사 기반 자동 퀴즈 생성 시작");

        quizPipelineService.generateQuizzesFromSelectedArticles();

        System.out.println("자동 퀴즈 생성 완료");
    }
}
