package oba.backend.server.scheduler;

import lombok.RequiredArgsConstructor;
import oba.backend.server.service.QuizPipelineService;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

/**
 * ✅ QuizScheduler
 * 매일 정해진 시각에 MongoDB → FastAPI → MySQL 파이프라인을 자동 실행
 */
@Component
@RequiredArgsConstructor
public class QuizScheduler {

    private final QuizPipelineService quizPipelineService;

    /**
     * 🕘 매일 오전 9시에 실행 (Asia/Seoul 기준)
     * - MongoDB에서 최근 뉴스 URL 5개 가져오기
     * - FastAPI에 전달 → GPT 퀴즈 생성
     * - MongoDB + MySQL 저장
     */
    @Scheduled(cron = "0 0 9 * * *", zone = "Asia/Seoul")
    public void autoGenerateDailyQuizzes() {
        System.out.println("🧠 [스케줄러] 오늘 뉴스 기반 퀴즈 자동 생성 시작");
        quizPipelineService.generateQuizzesFromMongo();
        System.out.println("✅ [스케줄러] 퀴즈 생성 완료");
    }
}
