package scheduler;

import lombok.RequiredArgsConstructor;
import oba.backend.server.service.QuizPipelineService;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

/**
 * ✅ QuizScheduler
 * - 매일 일정 시간마다 자동으로 실행되는 "스케줄링(Spring Scheduler)" 클래스
 * - 목적: 매일 오전 9시에 FastAPI를 호출해 새 뉴스 기반 퀴즈를 자동 생성
 */
@Component // ✅ 스프링이 관리하는 Bean 등록 (스케줄러 자동 감지 대상)
@RequiredArgsConstructor // ✅ final 필드 자동 생성자 주입 (DI)
public class QuizScheduler {

    // ✅ 퀴즈 자동 생성 파이프라인 서비스
    // - FastAPI 호출 + GPT 응답 + MySQL 저장 로직을 담당
    private final QuizPipelineService quizPipelineService;

    /**
     * 🕘 매일 오전 9시(서울 기준)에 자동 실행
     * - @Scheduled(cron = "0 0 9 * * *") 은 cron 표현식 기반 스케줄 설정
     * - zone = "Asia/Seoul" → 한국 시간 기준
     *
     * 동작 순서:
     *  1️⃣ 오전 9시가 되면 Spring이 자동으로 이 메서드를 호출
     *  2️⃣ QuizPipelineService.generateQuizzesFromSelectedArticles() 실행
     *  3️⃣ FastAPI로 URL 전송 → GPT 분석 → 퀴즈 생성 → MySQL 저장
     *  4️⃣ 콘솔 로그로 시작/완료 메시지 출력
     */
    @Scheduled(cron = "0 0 9 * * *", zone = "Asia/Seoul")
    public void autoGenerateDailyQuizzes() {
        System.out.println("🚀 [스케줄러] 오늘 기사 기반 자동 퀴즈 생성 시작");

        // ✅ 실제 퀴즈 생성 파이프라인 실행
        quizPipelineService.generateQuizzesFromSelectedArticles();

        System.out.println("✅ 자동 퀴즈 생성 완료");
    }
}
